### ISSUE TITLE
self-signed-tls.md is missing

### ISSUE THREAD

**Issue by rodibrin** [SAP/devops-docker-images#102]
The "cx-server-operations-guide.md" points to "operations/self-signed-tls.md" which does not exists.

**Comment by fwilhe** [comment]
Thank you @rodibrin for the notice, I added the file in #103

**Comment by rodibrin** [comment]
that's a fast fix

**Comment by fwilhe** [comment]
Yes, to be honest we forgot to move that file over from SAP/cloud-s4-sdk-pipeline :)
