### ISSUE TITLE
MTA-Archive-Builder node-gyp configure error

### ISSUE THREAD

**Issue by bmcdonn2** [SAP/devops-docker-images#107]
Hello all,

It appears that the latest version of the `mta-archive-builder` image now fails to build MTAs that include node modules requiring node-gyp for installation (`@sap/hana-client` for example). This is related to issue #55. 

This error does not occur when running the build using `mta-archive-builder:v1`.

Here's a log of the error:

```
> @sap/hana-client@2.3.123 install /localDebugRepo/application/node_modules/@sap/hdbext/node_modules/@sap/hana-client
> node build.js

{ Error: Command failed: node-gyp configure
Traceback (most recent call last):
  File "/opt/nodejs/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/opt/nodejs/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/opt/nodejs/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/nodejs/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/opt/nodejs/node-v10.13.0-linux-x64/bin/node" "/opt/nodejs/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /localDebugRepo/application/node_modules/@sap/hdbext/node_modules/@sap/hana-client
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure' } ''
```

Thanks,
Brian

**Comment by 1084565** [comment]
Hi Brian, can you specify what is missing in the Dockerfile to run your usecase?

**Comment by bmcdonn2** [comment]
Hey Chris,

My experience with Dockerfiles is very limited but if I had to guess I think this is the problematic code:

https://github.com/SAP/devops-docker-images/blob/9ae3595c170fb1d07077a6a5c84e6d0c284aa324/mta-archive-builder/Dockerfile#L70-L75

I think the recent inclusion of `--no-install-recommends` might be the reason this image now fails to build node modules that rely on node-gyp.

Hope this makes sense.

Thanks,

Brian

**Comment by lewingan** [comment]
docker pull latest for the mta-archive still has this python dependency error. is it because the docker hub image isn't updated?
we are currently using v1 as a workaround.

**Comment by fwilhe** [comment]
I faced the same error, and to my understanding we need to use the 'full' python instad of python-minimal, PR here https://github.com/SAP/devops-docker-images/pull/110

**Comment by fwilhe** [comment]
See also #111

**Comment by fwilhe** [comment]
Hi @bmcdonn2, @lewingan, can you test with the new `latest` tag of the image? In my case it worked now. I think this issue is resolved.

**Comment by bmcdonn2** [comment]
@fwilhe I ran my build on the image with the `latest` tag and everything worked as expected. Thanks for correcting this!
