### ISSUE TITLE
mta-archive-builder node-gyp configure error

### ISSUE THREAD

**Issue by lewingan** [SAP/devops-docker-images#116]
Hi all,

the latest ppiper/mta-archive-builder is once again failing. Same error as before which relates to the Python dependency. I am reverting back to v1 to get the build to work. Refer to issue #107 

-----
Hi @bmcdonn2, @lewingan, can you test with the new `latest` tag of the image? In my case it worked now. I think this issue is resolved.

_Originally posted by @fwilhe in https://github.com/SAP/devops-docker-images/issues/107#issuecomment-507635119_

**Comment by fwilhe** [comment]
Hi @lewingan,

I’m sorry about that. We build the image from a new repo now, and did not take the latest Dockerfile. I’ve just merged the change again, the image is building, after that the issue should be fixed again.

Kind regards

Florian
