### ISSUE TITLE
Support for 'Delta Mode' during node-rfc upload

### ISSUE THREAD

**Issue by stesap** [SAP/devops-docker-images#134]
Hi all,

we have the requirement to upload UI5 apps with delta mode. In the report which is used for the upload I can see this option next to "Accept Unix style...", which is already supported. Unfortunatel, delta mode checkbox is not available as an option within this docker container. Is it a missing thing in this repository or is it not available via node-rfc? In my understanding node-rfc tool supports all import parameters for all avail. function modules.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/57390068/87081394-9788e400-c229-11ea-8e7f-591605bf8ad4.png">

Thanks,
-Steffen

**Comment by radsoulbeard** [comment]
Hi Steffen,

we explicitly did not use the delta mode as it made some trouble in the past.

Best regards,
Thorsten
