### ISSUE TITLE
Docker images for On-premise system

### ISSUE THREAD

**Issue by himanshush13** [SAP/devops-docker-images#139]
Can we use the Docker files for On-premise systems, as Piper has got a wide range of solutions to CI/CD, but all of them are looking for cloud.

**Comment by daniel-kurzynski** [comment]
CI/CD is usually (with Jenkins) always On-Premise. What do you mean with Cloud. I think you can use the Docker images wherever you can install Docker. 
Could you please elaborate a little more on what your requirements? What you mean with On-Premise and Cloud in this context and why you think you cannot use  the Docker images?

**Comment by himanshush13** [comment]
I am kinda new to Docker, so it might seem to you as a naïve question. 
But, I am trying some CI steps on Azure DevOps for ABAP, I have experimented with UI5, and now I am trying for ABAP on-premise and thought of using Docker and, I couldn't find any document for the usage.

**Comment by fwilhe** [comment]
Hi, I'm still not clear on what your requirement is. Describing it a little more might help.

Those posts might be helpful to get you started:

* https://blogs.sap.com/2019/10/24/how-to-use-project-piper-docker-images-for-cicd-with-azure-devops/
* https://blogs.sap.com/2019/11/06/project-piper-and-azure-devops-successful-collaboration-with-delaware/
