### ISSUE TITLE
Can the project piper dockers instances be deployed to sap cloud platform (cloud foundry)?

### ISSUE THREAD

**Issue by js1972** [SAP/devops-docker-images#140]
I can deploy docker containers running my applications to cloud foundry. Can we also deploy the project piper docker containers to CF or it is specifically necessary to have some sort of block storage device attached meaning that they will not run on CF?

**Comment by fwilhe** [comment]
Hi @js1972 

I don't know what benefit you would have from using those images, but as the readme states, those images where made for running in Jenkins pipelines.

Quote from the readme:

> This is a collection of Dockerfiles for images that can be used in Continuous Delivery (CD) pipelines for SAP development projects. The images are optimized for use with project "Piper" on Jenkins. Docker containers simplify your CD tool setup, encapsulating tools and environments that are required to execute pipeline steps.

I guess your requirements are not what this repository tries to implement.

Best,

Florian

**Comment by js1972** [comment]
Hi @fwilhe 

You may be right. I thought project piper provided the whole kit to setup CI/CD - including Jenkins. Maybe I am reading it wrong but the project piper website links to here and also to here: https://hub.docker.com/r/ppiper/jenkins-master

So that second link looks like a Jenkins server in docker.
It seems that the other components to provide `mbt` and the cf cli etc are all provided in separate docker files.

So if this is the wrong place - apologies. But it does seem that you do Jenkins in docker as well so the question stands.. can that be deployed to sap cloud platform - cf runtime.
My thinking was that this is how sap does it cloud platform CI/CD service.

**Comment by radsoulbeard** [comment]
Hi @js1972 ,

to run the Jenkins docker images in cf runtime is not a good idea, that does not scale. Run it on a big VM or an K8S cluster.
You are right, the CI/CD service is Jenkins based but not in the cf runtime. For more details have a look here: https://github.com/SAP/stewardci-core

**Comment by js1972** [comment]
Hi Thorsten,

I’m just trying to get a better understanding here but a customer is not
charged based on the size of the docker container are they?

I thought they would just be charged based on the consumption of the
running Jenkins process (app runtime)?
