### ISSUE TITLE
Protect Master Branch

### ISSUE THREAD

**Issue by 1084565** [SAP/devops-docker-images#17]
I'm not sure this is set already, but I assume it's not (I can push to the master branch directly). @jonathanbaker7 , could you please take care of this?

Thanks!

**Comment by 1084565** [comment]
@jonathanbaker7 
Same settings as in our other repo:
https://github.com/SAP/jenkins-library/issues/104#

**Comment by CCFenner** [comment]
Done

![Bildschirmfoto 2019-04-10 um 15 41 11](https://user-images.githubusercontent.com/26137398/55883716-1b779a80-5ba7-11e9-8164-0594d5118379.png)
