### ISSUE TITLE
cx-server start fails when no custom-environment.list in workspace

### ISSUE THREAD

**Issue by fgeckeler** [SAP/devops-docker-images#50]
Starting the cx-server fails when there is no custom-environment.list file in the workspace.

Steps to reproduce:

1. cd into cx-server-companion/life-cycle-scripts
2. chmod +x cx-server
3. ./cx-server start

Expected behaviour:
* cx-server starts

Actual behaviour:
* the script exits without starting the container(s)
* Error: `docker: open custom-environment.list: no such file or directory.`

**Comment by fwilhe** [comment]
Fixed by #51
