### ISSUE TITLE
mta-archive-builder fails to clear directory .mta when not running as root

### ISSUE THREAD

**Issue by o-liver** [SAP/devops-docker-images#87]
`docker run --rm -v $PWD:/project -it ppiper/mta-archive-builder:latest mtaBuild --mtar dummy.mtar --build-target CF build` returns `ERROR: failed to clear directory .mta` when not running as root: `docker run -u root --rm -v $PWD:/project -it ppiper/mta-archive-builder:latest mtaBuild --mtar dummy.mtar --build-target CF build`

**Comment by o-liver** [comment]
Wrong from my side: I mounted a volume with a `.mta` dir into the container which could not be deleted by user mta!

**Comment by fvsgit** [comment]
@o-liver I am really new to docker but I understand some basics. I also tried to start the container and get exactly the same error. When I chekc the directory where I am executing the docker run command i see a hidden .mta directory. I then delete this directory and then execute the command as mentioned by SAP, but i get the same error. What do you mean with: "I mounted a volume with a .mta dir into the container which could not be deleted by user mta!" How should I mount the volume to avoid this?

**Comment by marcusholl** [comment]
Does this work for you:
```
docker run -it -v <YOUR_PROJECT_ROOT_DIR_ABSOLUTE>:/project  ppiper/mta-archive-builder mtaBuild --mtar <YOUR_MTAR_NAME> --build-target <CF or NEO> build
```
?

The folder you are mounting into needs to have sufficient write permissions. _For troubleshooting_ maybe `777`. The image uses by default user id 1000 (... corresponding user name `mta`).

**Comment by fvsgit** [comment]
Thanks for your help, managed to get it working.
